---
# These are the default variables common to most gitlab configuration roles
# gitlab_api_url
# gitlab_api_token
# gitlab_validate_certs

gitlab_project_branches: []
gitlab_project_branches_secure_logging: "{{ gitlab_configuration_secure_logging | default('false') }}"
gitlab_project_branches_async_retries: "{{ gitlab_configuration_async_retries | default(50) }}"
gitlab_project_branches_async_delay: "{{ gitlab_configuration_async_delay | default(1) }}"
gitlab_project_branches_loop_delay: "{{ gitlab_configuration_loop_delay | default(0) }}"
gitlab_project_branches_configuration_state: "{{ gitlab_configuration_state | default('present') }}"
gitlab_configuration_async_dir:
...