---

- name: Include tasks to share gitlab project
  ansible.builtin.include_tasks:
    file: share_gitlab_project.yml
  loop: "{{ gitlab_project_shares }}"
  loop_control:
    loop_var: __gitlab_project_shares_item
    label: "{{ __operation['verb'] }} GitLab Project {{ __gitlab_project_shares_item['name'] }}" 
    pause: "{{ gitlab_project_share_loop_delay }}"
  vars:
    __operation: "{{ operation_translate[__gitlab_project_shares_item.state | default(gitlab_configuration_state) | default('present')] }}"