---


- name: Manage GitLab Group Variables Block
  no_log: "{{ gitlab_group_variables_secure_logging }}"
  block:

    - name: GitLab Group Variables | Configuration
      community.general.gitlab_group_variable:
        api_url: "{{ gitlab_api_url }}"
        api_token: "{{ gitlab_api_token }}"
        validate_certs: "{{ gitlab_validate_certs | default(true) }}"
        group: "{{ __gitlab_group_variables_item['group'] }}"
        purge: "{{ __gitlab_group_variables_item['purge'] | default(gitlab_group_variables_purge) | default(false) }}"
        variables: "{{ __gitlab_group_variables_item['variables'] }}"
        state: "{{ __gitlab_group_variables_item['state'] | default(gitlab_configuration_state) | default('present') }}"
      loop: "{{ gitlab_group_variables }}"
      loop_control:
        loop_var: __gitlab_group_variables_item
        label: "{{ __operation['verb'] }} GitLab Group {{ __gitlab_group_variables_item['group'] }}" 
        pause: "{{ gitlab_group_variables_loop_delay }}"
      async: 1000
      poll: 0
      register: __gitlab_group_variables_job_async
      changed_when: not __gitlab_group_variables_job_async['changed']
      vars:
        __operation: "{{ operation_translate[__gitlab_group_variables_item.state | default(gitlab_configuration_state) | default('present')] }}"

    - name: GitLab Group Variables | Wait for configuration to finish
      when:
        - not ansible_check_mode
        - __gitlab_group_variables_job_async_results_item['ansible_job_id'] is defined
      ansible.builtin.include_role:
        name: bmcintyr.gitlab_configuration.collect_async_status
      loop: "{{ __gitlab_group_variables_job_async['results'] }}"
      loop_control:
        loop_var: __gitlab_group_variables_job_async_results_item
        label: "{{ __operation['verb'] }} GitLab Group {{ __gitlab_group_variables_job_async_results_item['__gitlab_group_variables_item']['group'] }} | Wait for GitLab Group {{ __operation['action'] }}" 
      vars:
        cas_secure_logging: "{{ gitlab_group_variables_secure_logging }}"
        cas_async_delay: "{{ gitlab_group_variables_async_delay }}"
        cas_async_retries: "{{ gitlab_group_variables_async_retries }}"
        cas_job_async_results_item: "{{ __gitlab_group_variables_job_async_results_item }}"
        cas_register_subvar: gitlab_group_variables
        cas_error_list_var_name: gitlab_group_variables_errors
        __operation: "{{ operation_translate[__gitlab_group_variables_job_async_results_item.__gitlab_group_variables_item.state | default(gitlab_configuration_state) | default('present')] }}"
        cas_object_label: "{{ __operation.verb }} GitLab Group Variables {{ __gitlab_group_variables_job_async_results_item.__gitlab_group_variables_item.group }} Wait for GitLab Group Variable {{ __operation['action'] }}"
  always:
    - name: Clean up async results files
      when:
        - not ansible_check_mode
        - __gitlab_group_variables_job_async_results_item['ansible_job_id'] is defined
      ansible.builtin.async_status:
        jid: "{{ __gitlab_group_variables_job_async_results_item['ansible_job_id'] }}"
        mode: cleanup
      loop: "{{ __gitlab_group_variables_job_async['results'] }}"
      loop_control:
        loop_var: __gitlab_group_variables_job_async_results_item
        label: "Cleaning up job results file: {{ __gitlab_group_variables_job_async_results_item['results_file'] | default('Unknown') }}"
      
...
