---


- name: Manage GitLab LDAP Group Links Block
  no_log: "{{ gitlab_ldap_group_links_secure_logging }}"
  block:

    - name: GitLab | Manage LDAP group links
      ansible.builtin.uri:
        url: "{{ gitlab_api_url }}/api/v4/groups/{{ __gitlab_ldap_group_links_item['group_name'] | urlencode }}/ldap_group_links"
        method: "{{ operation_translate[__gitlab_ldap_groups_item.state | default(gitlab_configuration_state) | default('present')] }}"
        headers:
          PRIVATE-TOKEN: "{{ gitlab_api_token }}"
        body_format: json
        body:
          cn: "{{ __gitlab_ldap_groups_item['cn'] }}"
          group_access: "{{ __gitlab_ldap_groups_item['access'] }}"
          provider: "{{ __gitlab_ldap_groups_item['provider'] | default(gitlab_ldap_group_links_ldap_provider) }}"
        status_code: [200, 201]
        validate_certs: "{{ gitlab_validate_certs | default(true) }}"
      loop: "{{ __gitlab_ldap_group_links_item['ldap_groups'] }}"
      loop_control:
        loop_var: __gitlab_ldap_groups_item
        label: "Manage GitLab LDAP Group Link {{ __gitlab_ldap_group_links_item['cn'] }}" 
        pause: "{{ gitlab_ldap_group_links_loop_delay }}"
      async: 1000
      poll: 0
      register: __gitlab_ldap_group_links_job_async
      changed_when: not __gitlab_ldap_group_links_job_async['changed']

    - name: GitLab LDAP Group Links | Wait for configuration to finish
      when:
        - not ansible_check_mode
        - __gitlab_ldap_group_links_job_async_results_item['ansible_job_id'] is defined
      ansible.builtin.include_role:
        name: truist.gitlab_configuration.collect_async_status
      loop: "{{ __gitlab_ldap_group_links_job_async['results'] }}"
      loop_control:
        loop_var: __gitlab_ldap_group_links_job_async_results_item
      vars:
        cas_secure_logging: "{{ gitlab_ldap_group_links_secure_logging }}"
        cas_async_delay: "{{ gitlab_ldap_group_links_async_delay }}"
        cas_async_retries: "{{ gitlab_ldap_group_links_async_retries }}"
        cas_job_async_results_item: "{{ __gitlab_ldap_group_links_job_async_results_item }}"
        cas_register_subvar: gitlab_ldap_group_links
        cas_error_list_var_name: gitlab_ldap_group_links_errors
        cas_object_label: "Manage GitLab LDAP Group Links {{ __gitlab_ldap_group_links_job_async_results_item }} Wait for GitLab Group LDAP Link"

  always:
    - name: Clean up async results files
      when:
        - not ansible_check_mode
        - __gitlab_ldap_group_links_job_async_results_item['ansible_job_id'] is defined
      ansible.builtin.async_status:
        jid: "{{ __gitlab_ldap_group_links_job_async_results_item['ansible_job_id'] }}"
        mode: cleanup
      loop: "{{ __gitlab_ldap_group_links_job_async['results'] }}"
      loop_control:
        loop_var: __gitlab_ldap_group_links_job_async_results_item
        label: "Cleaning up job results file: {{ __gitlab_ldap_group_links_job_async_results_item['results_file'] | default('Unknown') }}"
      
     



...
